from datetime import date

TODAY = date.today().strftime("%Y-%m-%d")

BASE_URL_MAP = {"realtor.com": "https://www.realtor.com"}

WEB_PAGE_DELIMITER = ""

ROTATE_PROXY_OFFSET = 600_000

CITY_LIST = ['Austin, TX',
 'Nashville, TN',
 'Fort Worth, TX',
 'Seattle, WA',
 'Henderson, NV',
 'Raleigh, NC',
 'Charlotte, NC',
 'Denver, CO',
 'Dallas, TX',
 'Mesa, AZ',
 'Aurora, CO',
 'Phoenix, AZ',
 'Tampa, FL',
 'Colorado Springs, CO',
 'Arlington, TX',
 'Portland, OR',
 'Atlanta, GA',
 'Houston, TX',
 'San Jose, CA',
 'Miami, FL',
 'Jacksonville, FL',
 'San Diego, CA',
 'Sacramento, CA',
 'Riverside, CA',
 'Las Vegas, NV',
 'Anaheim, CA',
 'Santa Ana, CA',
 'San Antonio, TX',
 'El Paso, TX',
 'Columbus, OH',
 'Minneapolis, MN',
 'Fresno, CA',
 'Lexington, KY',
 'Tucson, AZ',
 'Bakersfield, CA',
 'Oklahoma City, OK',
 'Stockton, CA',
 'Boston, MA',
 'Washington, DC',
 'Omaha, NE',
 'San Francisco, CA',
 'St. Paul, MN',
 'Los Angeles, CA',
 'Oakland, CA',
 'Corpus Christi, TX',
 'Long Beach, CA',
 'Kansas City, MO',
 'Virginia Beach, VA',
 'Pittsburgh, PA',
 'Albuquerque, NM',
 'Memphis, TN',
 'Wichita, KS',
 'Honolulu, HI',
 'Louisville, KY',
 'Indianapolis, IN',
 'Tulsa, OK',
 'Milwaukee, WI',
 'Cincinnati, OH',
 'Philadelphia, PA',
 'New York, NY',
 'Detroit, MI',
 'Chicago, IL',
 'New Orleans, LA',
 'Baltimore, MD',
 'Cleveland, OH',
 'St. Louis, MO',
 'Frisco, TX',
 'McKinney, TX',
 'Cary, NC',
 'Gilbert, AZ',
 'Peoria, AZ',
 'Durham, NC',
 'Port St. Lucie, FL',
 'Plano, TX',
 'Chandler, AZ',
 'Grand Prairie, TX',
 'Boise, ID',
 'Irving, TX',
 'Vancouver, WA',
 'Tempe, AZ',
 'Fort Collins, CO',
 'Irvine, CA',
 'Orlando, FL',
 'Salt Lake City, UT',
 'Elk Grove, CA',
 'Sunnyvale, CA',
 'Eugene, OR',
 'Huntsville, AL',
 'Reno, NV',
 'Tacoma, WA',
 'Garland, TX',
 'Cape Coral, FL',
 'Madison, WI',
 'Scottsdale, AZ',
 'Glendale, AZ',
 'Salem, OR',
 'North Las Vegas, NV',
 'Spokane, WA',
 'Ontario, CA',
 'Fremont, CA',
 'Chula Vista, CA',
 'Overland Park, KS',
 'Lincoln, NE',
 'Lakewood, CO',
 'Knoxville, TN',
 'St. Petersburg, FL',
 'Hayward, CA',
 'Fontana, CA',
 'Rancho Cucamonga, CA',
 'Corona, CA',
 'Modesto, CA',
 'Oceanside, CA',
 'Pembroke Pines, FL',
 'Hialeah, FL',
 'Chesapeake, VA',
 'Salinas, CA',
 'Santa Clarita, CA',
 'Escondido, CA',
 'Greensboro, NC',
 'Moreno Valley, CA',
 'Grand Rapids, MI',
 'Santa Rosa, CA',
 'San Bernardino, CA',
 'Pomona, CA',
 'Garden Grove, CA',
 'Alexandria, VA',
 'Richmond, VA',
 'Oxnard, CA',
 'Fort Wayne, IN',
 'Springfield, MO',
 'Huntington Beach, CA',
 'Tallahassee, FL',
 'Jersey City, NJ',
 'Laredo, TX',
 'Amarillo, TX',
 'Augusta, GA',
 'Winston-Salem, NC',
 'Glendale, CA',
 'Birmingham, AL',
 'Palmdale, CA',
 'Lancaster, CA',
 'Worcester, MA',
 'Buffalo, NY',
 'Norfolk, VA',
 'Fort Lauderdale, FL',
 'Newport News, VA',
 'Rochester, NY',
 'Little Rock, AR',
 'Akron, OH',
 'Fayetteville, NC',
 'Hollywood, FL',
 'Des Moines, IA',
 'Anchorage, AK',
 'Providence, RI',
 'Aurora, IL',
 'Mobile, AL',
 'Montgomery, AL',
 'Yonkers, NY',
 'Springfield, MA',
 'Jackson, MS',
 'Newark, NJ',
 'Toledo, OH',
 'Columbus, GA',
 'Baton Rouge, LA',
 'Shreveport, LA',
 'Allen, TX',
 'Denton, TX',
 'Richardson, TX',
 'Murfreesboro, TN',
 'Bellevue, WA',
 'Carrollton, TX',
 'Surprise, AZ',
 'Roseville, CA',
 'Hillsboro, OR',
 'Arvada, CO',
 'Clovis, CA',
 'Thornton, CO',
 'Longmont, CO',
 'Renton, WA',
 'Everett, WA',
 'Santa Clara, CA',
 'Spokane Valley, WA',
 'Greeley, CO',
 'Westminster, CO',
 'Davie, FL',
 'Charleston, SC',
 'Athens-Clarke, GA',
 'North Charleston, SC',
 'Palm Bay, FL',
 'Kent, WA',
 'Beaverton, OR',
 'Vacaville, CA',
 'Lakeland, FL',
 'Wilmington, NC',
 'Chico, CA',
 'Temecula, CA',
 'Mesquite, TX',
 'Roswell, GA',
 'Fairfield, CA',
 'Norman, OK',
 'Visalia, CA',
 'Cambridge, MA',
 'Miramar, FL',
 'Vista, CA',
 'West Palm Beach, FL',
 'Federal Way, WA',
 'Carlsbad, CA',
 'Boulder, CO',
 'Santa Maria, CA',
 'Rialto, CA',
 'Sterling Heights, MI',
 'Sunrise, FL',
 'Gresham, OR',
 'Yuma, AZ',
 'San Mateo, CA',
 'Quincy, MA',
 'Daly City, CA',
 'High Point, NC',
 'Yakima, WA',
 'Plantation, FL',
 'Murrieta, CA',
 'Centennial, CO',
 'Mission Viejo, CA',
 'Victorville, CA',
 'Broken Arrow, OK',
 'Ventura, CA',
 'Ann Arbor, MI',
 'Antioch, CA',
 'Costa Mesa, CA',
 'Berkeley, CA',
 'Clearwater, FL',
 'Westminster, CA',
 'Pueblo, CO',
 'West Covina, CA',
 'Boca Raton, FL',
 'Orange, CA',
 'Burbank, CA',
 'Sandy Springs, GA',
 'Green Bay, WI',
 'Gainesville, FL',
 'Concord, CA',
 'Thousand Oaks, CA',
 'Miami Gardens, FL',
 'Pasadena, CA',
 'Naperville, IL',
 'Fullerton, CA',
 'Simi Valley, CA',
 'El Cajon, CA',
 'South Gate, CA',
 'Coral Springs, FL',
 'Warren, MI',
 'Livonia, MI',
 'Savannah, GA',
 'Kenosha, WI',
 'Richmond, CA',
 'Santa Monica, CA',
 'El Monte, CA',
 'Torrance, CA',
 'Manchester, NH',
 'Vallejo, CA',
 'Carson, CA',
 'Santa Barbara, CA',
 'Fort Smith, AR',
 'Dearborn, MI',
 'Downey, CA',
 'Norwalk, CA',
 'Tuscaloosa, AL',
 'Roanoke, VA',
 'Lansing, MI',
 'Inglewood, CA',
 'Pompano Beach, FL',
 'Lynn, MA',
 'Lowell, MA',
 'Cedar Rapids, IA',
 'Compton, CA',
 'Fall River, MA',
 'Springfield, IL',
 'New Bedford, MA',
 'Hampton, VA',
 'Stamford, CT',
 'Albany, NY',
 'Waukegan, IL',
 'Allentown, PA',
 'Dayton, OH',
 'Erie, PA',
 'Brockton, MA',
 'New Haven, CT',
 'Flint, MI',
 'Davenport, IA',
 'Miami Beach, FL',
 'Elgin, IL',
 'Joliet, IL',
 'Elizabeth, NJ',
 'Waterbury, CT',
 'Portsmouth, VA',
 'Paterson, NJ',
 'Rockford, IL',
 'Hartford, CT',
 'Bridgeport, CT',
 'Peoria, IL']
